spring.application.name=backend

# Configuracion de MySQL - Aiven
spring.datasource.url=jdbc:mysql://palasada-database-palasada.e.aivencloud.com:12587/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_iSEIT2YhN3vStpEFwlE

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true